### ISSUE TITLE
lighting coherence and img2img depthmask for 1.5

### ISSUE THREAD

**Issue by 2blackbar** [Extraltodeus/multi-subject-render#8]
1. HEy, do you know how to solve coherence with light? subjects dont really fit into the bacgkgrounds, even on your examples its daylight sun on girls but the room is lit by practical lamps ,also it doesnt hit all subjects from the same angle like it should if theyd be there together in the scene...
How to solve this i have no idea, i think now its like copy paste from different photos to completely random bg.Works ok mostly with flat comics subjects.With realistic stuff it wont, maybe a bit with overcast lighting.
Would be great it the code would compare light from background , the angle and use it to synthesize subjects...

2 that depth mask is great, when it will be available for regular 1.5 models trained on dreambooth? That should give people much better coherence between multiple images, cant wait for this one, would be nice if this would be separate extension or actually added into the main repo but auto1111 isnt as active nowadays., big git pull requests queue ...

**Comment by Extraltodeus** [comment]
1. It's all about the blend img2img at the end! I already noticed that SD would  even reorganise the shadows to put them in the same direction. Really if you feel like it's too much of a collage then you should add more steps or denoising. Unfortunately like with all things related to stable diffusion it is quite hard to have a sure way to get the right settings besides testing and playing around with the settings.

2. Check my readme in here. It is already possible to make a depth aware mask for img2img. I need to make one more script specially for that purpose with more choices with the midas models to struggle less with the depth recognition and have a more detailed depth (right now that extension is using the lightest midas model so it's more or less just fore/background recognition).

Auto is not alone on the repository.

I'm closing this since it's not an issue. I enabled the discussions which is more suited for that kind of stuff.
